config/routes.rb
Webapps::Engine.routes.draw do
	# root of the plugin
        root :to => 'webapps#index'
        post "/" => "webapps#create"
    resources :webapps do
		member do
			delete 'delete'
			get 'new_name_check'
			get 'new_path_check'
			put 'update_name'
			put 'update_path'
			get 'toggle_login_required'
			post 'webapp_alias_create'
			delete 'webapp_alias_destroy'
			post 'add_permission'
			delete 'remove_permission'
		end
	end
	get "permissions" => "webapps#permissions"
	# examples of controllers built in this generator. delete at will
end

app/models/webapp_access.rb
# Amahi Home Server
# Copyright (C) 2007-2013 Amahi
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v3
# (29 June 2007), as published in the COPYING file.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# file COPYING for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Amahi
# team at http://www.amahi.org/ under "Contact Us."

require 'command'
require 'platform'


class WebappAccess < ActiveRecord::Base

	belongs_to :webapps

	def getUsers
		user_ids = JSON.parse(self.access_to)
		@users_allowed = []
		user_ids.each do |user_id|
			user = User.where(:id=>user_id).first
			@users_allowed << user if user
		end
		@users_allowed
	end

	def remove_all_users
		self.access_to = [].to_s
		self.save!
	end

	def addUser(user,password)
		users = JSON.parse(self.access_to)
		if(!users.include?(user.id))
			users = users << user.id
		end
		self.access_to = users.to_s
		self.save!
		webapp = Webapp.find(self.webapp_id)
		path = webapp.path
		htpasswd_path = path+'/htpasswd'
		if(File.file?(htpasswd_path))
			c = Command.new "htpasswd -bm #{htpasswd_path} #{user.login} #{password}"
		else
			c = Command.new "htpasswd -cbm #{htpasswd_path} #{user.login} #{password}"
		end
			c.execute
		Platform.reload(:apache)
	end

	def removeUser(user)
		users = JSON.parse(self.access_to)
		if(users.include?(user.id))
			users.delete(user.id)
		end
		self.access_to = users.to_s
		self.save!
		webapp = Webapp.find(self.webapp_id)
		path = webapp.path
		htpasswd_path = path+'/htpasswd'
		if(File.file?(htpasswd_path))
			c = Command.new "htpasswd -D #{htpasswd_path} #{user.login}"
			c.execute
		end
		Platform.reload(:apache)

	end

	def self.find_or_create(webapp_id)
		webapp_access = WebappAccess.where(:webapp_id=>webapp_id).first
		if(webapp_access == nil)
			webapp_access = WebappAccess.create(:webapp_id=>webapp_id,:access_to=>[].to_s)
		end
		webapp_access
	end
end

app/controllers/webapps_controller.rb
class WebappsController < ApplicationController
	before_action :admin_required

	def index
		@webapps = Webapp.all
	end

	def create
		name = params[:webapp][:name].strip
		path = params[:webapp][:path].sub(/\/+$/, '')
		path.gsub!(/\/+/, '/')
		@wa = Webapp.create(:name => name, :path => path)
		@webapps = Webapp.all
		# render :partial => 'content'
	end

	def delete
		wa = Webapp.find params[:id]
		wa.destroy
		@webapps = Webapp.all
	end

	def new_name_check(n)
		if n.nil? or n.blank?
			return false
		end
		if (not (valid_name?(n))) or (n.size > 32)
			return false
		end
		n = n.strip
		a = DnsAlias.where(:name => n).first
		if a.nil?
			# no such alias, ok to create it
			return true
		else
			return false
		end
	end

	def new_path_check(n)
		if n.nil? or n.blank?
			return false
		end
		unless valid_path?(n)
			return false
		end
		return true
	end

	def update_name
		id = params[:id]
		wa = Webapp.find(id)
		status = 'notok'
		unless params[:name].blank?
			name = params[:name]
			if new_name_check(name)
				if wa.update_attributes(:name=>name)
					status = 'ok'
				end
			else
				status = "notok"
			end
		end
		@webapp = wa
	end

	def update_path
		id = params[:id]
		wa = Webapp.find(id)
		unless params[:path].blank?
			path = params[:path]
			if new_path_check(path)
			# check it exists!
				if files_exist?(path)
					check = true
					wa.path = path
					wa.save!
					status = "ok"
				else
					# FIXME - report (somehow) why we did not
					# make it! user must be confused!?!
					# alternatively, create it!
					status = "notok"
				end
			else
				status = "notok"
			end
		end
		@webapp = wa
	end

	def toggle_login_required
		begin
			webapp = Webapp.find params[:id]
			webapp.login_required = ! webapp.login_required
			webapp.save
		rescue
		end
		render :json => {:status => 'ok'}
	end


	def webapp_alias_create
		@webapp = Webapp.find params[:id]
		raise "Webapp with id=#{params[:id]} cannot be found" unless @webapp
		@waa = WebappAlias.where(:name=>params[:name]).first
		if @waa
			prev = @waa.webapp_id
			@waa.webapp_id = @webapp.id
			@waa.save!
			Webapp.find(prev).save
		else
			@waa = WebappAlias.create(:name => params[:name], :webapp_id => @webapp.id)
		end

	end

	def webapp_alias_destroy
		@waa = WebappAlias.find(params[:id])
		id = @waa.webapp_id
		@waa.destroy if @waa
		@webapp = Webapp.find(id)
		return unless @waa
	end

	def permissions
		@webapps = Webapp.where(:login_required=>1)
		@users = User.all

	end

	def remove_permission
		@user = User.find(params[:id]) if params[:id]
		@webapp = Webapp.find(params[:webapp_id]) if params[:webapp_id]
		check = false
		if (@user && @webapp)
			w = WebappAccess.find_or_create(@webapp.id)
			w.removeUser(@user)
			@users_allowed = WebappAccess.find_or_create(@webapp.id).getUsers
			check = true
		end
		@status = check ? "ok" : "notok"
		@users_allowed = WebappAccess.find_or_create(@webapp.id).getUsers
	end

	def add_permission
		password = params[:password]
		@user = User.find(params[:id]) if params[:id]
		@webapp = Webapp.find(params[:webapp_id]) if params[:webapp_id]
		if (@user && @webapp)
			check = @user.valid_password?(password)
			if(check)
				w = WebappAccess.find_or_create(@webapp.id)
				w.addUser(@user,password)
			end
		end
		@status = check ? "ok" : "Wrong password"
		@users_allowed = WebappAccess.find_or_create(@webapp.id).getUsers
	end

private

	def valid_name?(nm)
		return false unless (nm =~ /\A[A-Za-z][A-Za-z0-9\-]+\z/)
		true
	end

	def valid_path?(path)
		return false if path.size > 250
		return false unless path =~ /^\//
		return false unless path =~ /\A[A-Za-z0-9_\/-]+\z/
		return false if path =~ /\/$/
		return false if path =~ /\/\/+/
		true
	end

	def files_exist?(path)
		return false unless File.exist?(path)
		return false unless File.exist?(File.join(path, "html"))
		return false unless File.exist?(File.join(path, "logs"))
		true
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/webapps/_content.html.slim
=render 'list'
=render 'new'

app/views/webapps/_form.html.slim
= form_for :webapp, :url => webapps_engine.root_path,
    :remote => true, \
    :html => { \
      :data => { \
        :ok_icon_path => theme_image_path('ok.png'), \
        :error_icon_path => theme_image_path('stop.png') \
      }, \
      :class => 'webapp create-form form-horizontal p-1 mt-2 bg-white d-inline-block', \
      :id => 'webapp-new' \
    } do |f|

    fieldset
      legend &nbsp; #{t 'create_a_new_webapp'} &nbsp;
      .create-inside
        .control-group.form-group
          .controls= f.text_field :name, :size => 16, :maxlength => 20, :value=>'', :placeholder => t('name'), :class=>'form-control', :id=>"webapp_name"

        .control-group.form-group
          .controls
          	=f.text_field :path, :size => 16, :maxlength => 64, :value=>'', :placeholder => t('root_path').html_safe, :class=>'form-control', :id=>"webapp_path"
          	b="/html"
        .control-group.form-group.create-btn
          .controls.col-xs-offset-2.col-xs-10
            = spinner
            = button_tag t('create'), :type => 'submit', :id => 'webapp_create_button', :class => 'btnn btn btn-info'
            = link_to t('cancel'), '#', :class => 'close-area cancel-link cancel-btn-style btn-sm left-margin-10', :data => {:related => '#new-webapp-to-step1'}

app/views/webapps/_list.html.slim
.settings-table#webapps-table
  - if @webapps.size > 0
    table.settings
      thead
        tr
          th.settings-col1.webapps-col1 scope="col" = t 'name'
          th.settings-col2.webapps-col2 scope="col" = t 'url'
      tbody
    = render :partial => 'webapp', :collection => @webapps
  - else
    div align="center"
      div align="left"
        h2= t 'there_are_no_webapps'
        p Web apps are web-based applications hosted in your Amahi HDA.
        p
          | Example of web apps are
          a href="http://www.wordpress.org" target="_blank"  Wordpress
          |,
          a href="http://www.mediawiki.org" target="_blank"  MediaWiki
          |,
          a href="http://gallery.menalto.com/" target="_blank"  Gallery
          |,
          a href="http://www.webmin.com/" target="_blank"  Webmin
          | and
          a href="http://phpsysinfo.sourceforge.net/" target="_blank"  PHPSysinfo
        p There are a myriad of other apps that run under Linux.
        p You can install web apps in this panel by:
        p
          ul
            li
              | Deciding what
              b " name"
              | you want to access the web app within your network (e.g. http://blog), and
            li
              | Selecting where is the
              b " root directory"
              | of the app you want to run
        p The application code is expected to be present (before or after configuring the app) in the root directory.
        p You can install it there as an archive from source (tar/zip), or as a package from existing applications in the base OS.
        p Currently supported are applications based on LAMP (PHP), Python, static pages and others.
        p
          | We have a small
          a href="http://wiki.amahi.org/index.php/Category:Apps" target="_blank"  gallery of apps
          | that other Amahi
          | developers and users have tried and tested.

app/views/webapps/_login_required.html.slim
- id = "login_required_#{webapp.id}"
span id=id
	= tag "input", class: "webapp-login remote-check", type: "checkbox", checked: webapp.login_required,
	              data: { remote: true, url: webapps_engine.toggle_login_required_webapp_path(id: webapp.id),
	              confirm: "Are you sure you want to require login?" }, :method=>"put"
	= spinner

app/views/webapps/_name.html.slim
a.click_change  = h(@webapp.name)
= simple_remote_text     :id => "name_#{@webapp.id}",
                         :input_id =>"name_webapp_#{@webapp.id}",
                         :form_id => "name_form_webapp_#{@webapp.id}",
                         :button_id => "new_name_webapp_#{@webapp.id}",
                         :url => webapps_engine.update_name_webapp_path(:id => @webapp.id),
                         :label => t("update"),
                         :name => :name,
                         :method => :put,
                         :remote => true,
                         :form_css_class => "edit_form form_hidden form-inline",
                         :cancel_class => "cancel_link btn-primary btn left-margin-10 btn-sm "

app/views/webapps/_new.html.slim
= button_tag "#{t('new_web_app')}" , :type => 'button', :class => 'open-area btnn btn btn-info', :id => "new-webapp-to-step1",  :data => { :related => "#new-webapp-step1" }

#new-webapp-box
  #webapp-new
    #new-webapp-step1.area[style="display:none;"]
      = render 'form'

app/views/webapps/_path.html.slim
a.click_change  = h(@webapp.path)
= simple_remote_text    :id => "path_#{@webapp.id}",
                         :input_id =>"path_webapp_#{@webapp.id}",
                         :form_id => "path_form_webapp_#{@webapp.id}",
                         :button_id => "new_path_webapp_#{@webapp.id}",
                         :url => webapps_engine.update_path_webapp_path(:id => @webapp.id),
                         :label => t("update"),
                         :name => :path,
                         :method => :put,
                         :remote => true,
                         :form_css_class => "edit_form form_hidden form-inline",
                         :cancel_class => "cancel_link btn-primary btn left-margin-10 btn-sm"

app/views/webapps/_permission_webapp.html.slim
- @webapp = webapp
- return if @webapp.nil?
- uid = @webapp.id.to_s
- @users_allowed = WebappAccess.find_or_create(@webapp.id).getUsers
div.webapp[id="whole_webapp_#{uid}"]
  table.settings.table.stretchtoggle id="webapp_row_#{uid}"
    tr
      td.settings-col1.webapps-col1.settings-col1-pad
        = link_to(@webapp.name, '')
      td.settings-col2.webapps-col2 id="webapp_url_#{uid}"
        a href=("http://#{webapp.name}") target="_blank"
          | http://#{@webapp.name}
  .settings-stretcher id="webapp_info_#{uid}" style="display:none;"
    .webapp-manage
      fieldset
        legend
          |&nbsp; #{t 'edit_web_app_access_for'}&nbsp;
          b= h(@webapp.name)
          | &nbsp;
        .settings-fields
          table.table
            -for item in @users
              -@user = item
              tr[id="permission_webapp#{@webapp.id}_user#{@user.id}"]
                = render :partial=>'user_permissions'

app/views/webapps/_user_permissions.html.slim
-checked = @users_allowed.include?@user

td = @user.name
td
	div
	- if checked
		= link_to("[x]",webapps_engine.remove_permission_webapp_path(:id => @user.id,:webapp_id=>@webapp.id), {:remote=>true, :method=>:delete, :class=>'edit_form user_access_delete_icon'})
	- else
	  	a.click_change  Add access password
	    form.edit_form.form_hidden.form-inline action=webapps_engine.add_permission_webapp_path(:id => @user.id,:webapp_id=>@webapp.id) data-remote="true" method="post" style=("display: none;")
			input.form-control.input-sm  name="password" type="password" placeholder="Enter User login password"
			| &nbsp;&nbsp;&nbsp;
		    button.btnn.btn.btn-create.margin-for-message.btn-info.left-margin-10.btn-sm type="submit" = t('add')
		    a.cancel_link.btn-primary.btn.left-margin-10.btn-sm Cancel
		    span.spinner.theme-image style=("display: none")
		    .messages

app/views/webapps/_webapp.html.slim
- delete_icon = theme_image_tag("delete", :title => t('delete_web_app'))
- webapp = webapp
- uid = webapp.id.to_s
- return if webapp.nil?

div.webapp[id="whole_webapp_#{uid}"]
  table.webapp-table-row.settings.stretchtoggle.table-condensed id="webapp_row_#{uid}"
    tr
      td.settings-col1.webapps-col1.settings-col1-pad
        = link_to(webapp.name, '')
      td.settings-col2.webapps-col2 id="webapp_url_#{uid}"
        a href=("http://#{webapp.name}") target="_blank"
          | http://#{webapp.name}
  .settings-stretcher id="webapp_info_#{uid}" style="display:none;"
    .webapp-manage
      fieldset
        legend
          |&nbsp; #{t 'edit_web_app'}&nbsp;
          b= h(webapp.name)
          | &nbsp;
        .settings-actions
          = spinner uid
          - if webapp.deletable
            span.delete
            = spinner
            = link_to ("Delete web app "+ webapp.name), webapps_engine. delete_webapp_path(webapp),
                      :remote => true,
                      :method => :delete,
                      :id => "delete-webapp-#{webapp.id}",
                      :data => { :confirm => "Are you sure you want to delete "+ webapp.name},
                      :class => 'btn-delete remote-btn navbar-right btn btn-sm d-inline-block'
        .settings-fields
          table.table-condensed
            tr
              td
                = t 'name'

              td &nbsp;
              td
                - if webapp.deletable
                  span id="webapp_name_#{webapp.id}" = render :partial => 'name', :locals => { :@webapp => webapp }

                - else
                  = h webapp.name

            tr
              td
                = t 'aliases'
              td &nbsp;
              td
                = render :partial => 'webapp_aliases', :locals => { :@webapp => webapp }
              td

            tr
              td
                = t('root_path').html_safe

              td &nbsp;
              td
                - if webapp.deletable
                  span id="webapp_path_#{webapp.id}" = render :partial => 'path', :locals => { :@webapp => webapp }
                - else
                  = h(webapp.path)
                  | /html/

            tr
              td
                = t 'logs'

              td &nbsp;
              td
                = h(webapp.path)
                | /logs/

            tr
              td
                = t 'url'

              td &nbsp;
              td
                a href=("http://#{h webapp.name}") target="_"
                  | http://#{h webapp.name}

            tr
              td
                = t 'access'

              td &nbsp;
              td valign="top"
                = render :partial => 'login_required', :locals => { :webapp => webapp }

            tr
              td
                = t 'created'

              td &nbsp;
              td
                = d = webapp.created_at.localtime; d.to_formatted_s(:short) + " (" + time_ago_in_words(d) + ")"

app/views/webapps/_webapp_aliases.html.slim
- uid = @webapp.id.to_s
div id="webapp_aliases_#{uid}"
  div id="webapp_aliases_new_#{uid}"
  	a.click_change  New alias
    = simple_remote_text    :id => "#{@webapp.id}",
                             :input_id =>"text_webapp_#{@webapp.id}",
                             :form_id => "form_webapp_#{@webapp.id}",
                             :button_id => "new_alias_webapp_#{@webapp.id}",
                             :url => webapps_engine.webapp_alias_create_webapp_path(:id => @webapp.id),
                             :label => t("add"),
                             :name => :name,
                             :method => :post,
                             :remote => true,
                             :form_css_class => "edit_form form_hidden form-inline",
                             :cancel_class => "cancel_link btn-primary btn left-margin-10 btn-sm"
    .messages


  - for a in @webapp.webapp_aliases.map do
  	br/
  	= link_to("[x]",webapps_engine.webapp_alias_destroy_webapp_path(:id => a.id), {:remote=>true, :method=>:delete, :class=>'edit_form alias-delete-icon'})

  	= link_to("http://#{a}", " http://#{a}", { :target => '_blank'})

app/views/webapps/index.html.slim
= stylesheet_link_tag 'webapp_style'
= javascript_include_tag 'webapps'
= render 'content'

app/views/webapps/permissions.html.slim
= stylesheet_link_tag 'webapp_style'
= javascript_include_tag 'webapps'

.settings-table#permissions
  - if @webapps.size > 0
    table.settings.table
      thead
        tr
          th.settings-col1.webapps-col1 scope="col" = t 'name'
          th.settings-col2.webapps-col2 scope="col" = t 'url'
      tbody
    = render :partial => 'permission_webapp', :collection => @webapps, :as=> :webapp
  - else
    div align="center"
        div align="left"
          h2= t 'there_are_no_webapps'